[build]
  publish = "."
  functions = "hivetag-netlify/functions"

[functions]
  node_bundler = "esbuild"

[context.production.environment]
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

