// supabase/functions/_shared/emailTemplates.ts

export const EMAIL_TEMPLATES = {
  WELCOME: 3,
  PREMIUM_WELCOME: 4,
  SUBSCRIPTION_CANCELLED: 5,
  SUBSCRIPTION_RENEWED: 6,
  PAYMENT_FAILED: 7,
  PASSWORD_CHANGED: 8,
  ACCOUNT_DELETED: 9,

  DONATION_THANK_YOU: 15,

  NFC_ORDER_CONFIRMATION: 16,
  NFC_INTERNAL_ORDER_NOTIFICATION: 17,
  NFC_DISPATCH_CONFIRMATION: 18,

  INTERNAL_NEW_PREMIUM_SUBSCRIBER: 19,
  INTERNAL_PAYMENT_FAILED: 20,
  INTERNAL_SUBSCRIPTION_CANCELLED: 21,
} as const;