const SUPABASE_URL = 'https://uihngfpmoasnofyrvpmw.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpaG5nZnBtb2Fzbm9meXJ2cG13Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MjM3MTYxMSwiZXhwIjoyMDY3OTQ3NjExfQ.CcXllxhkkinxXKUzVYd4PUtKj653OtzXlLjtn8Rfi5c';

const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

